/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    formats: ['image/avif', 'image/webp'],
    deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
    loader: 'default',
    minimumCacheTTL: 60,
    dangerouslyAllowSVG: true,
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
  },
  // Optimisations de compilation
  compiler: {
    removeConsole: process.env.NODE_ENV === 'production',
  },
  // Optimisations CSS et JS
  swcMinify: true,
  compress: true,
  poweredByHeader: false,
  // Performance
  reactStrictMode: true,
  async redirects() {
    const templateRoutes = [
      '/accordion',
      '/advance-pricing',
      '/advance-tab',
      '/blog-grid',
      '/blog-grid-sidebar',
      '/blog-list-sidebar',
      '/blog-list-view',
      '/brand',
      '/brand-carouse',
      '/button',
      '/call-to-action',
      '/counter',
      '/error',
      '/gallery',
      '/index-application',
      '/index-business',
      '/index-business-consulting',
      '/index-business-consulting-2',
      '/index-collaborate',
      '/index-company',
      '/index-consulting',
      '/index-corporate',
      '/index-corporate-one-page',
      '/index-creative-portfolio',
      '/index-digital-agency',
      '/index-event-conference',
      '/index-finance',
      '/index-freelancer',
      '/index-international-consulting',
      '/index-landing',
      '/index-magazine',
      '/index-marketing-agency',
      '/index-personal-portfolio',
      '/index-photographer',
      '/index-seo-agency',
      '/index-startup',
      '/index-travel-agency',
      '/index-web-agency',
      '/login',
      '/portfolio-box-layout',
      '/portfolio-full-width',
      '/portfolio-grid-layout',
      '/portfolio-three-column',
      '/pricing',
      '/progressbar',
      '/service',
      '/social-share',
      '/split',
      '/tab',
      '/team',
      '/testimonial',
      '/timeline',
      '/video',
    ];

    return [
      { source: '/en', destination: '/en/index-digital-agency', permanent: true },
      { source: '/es', destination: '/es/index-digital-agency', permanent: true },
      { source: '/de', destination: '/de/index-digital-agency', permanent: true },
      { source: '/it', destination: '/it/index-digital-agency', permanent: true },
      ...templateRoutes.map((source) => ({
        source,
        destination: '/',
        permanent: true,
      })),
    ];
  },
};

export default nextConfig;
